import type { KbCategory } from "@/generated/prisma";

export const KB_CATEGORY_LABEL: Record<KbCategory, string> = {
  BLENDING_SOP: "Blending SOP",
  MACHINE_TROUBLESHOOTING: "Machine Troubleshooting",
  MAINTENANCE_CLEANING: "Maintenance & Cleaning",
  SAFETY: "Safety",
  PARTS: "Parts & Tooling",
  QUALITY_CONTROL: "Quality Control",
  QUALITY_ASSURANCE: "Quality Assurance",
  HACCP: "HACCP",
  SQF: "SQF",
  GMP: "GMP",
  GDP: "Good Documentation Practice (GDP)",
  FOOD_SAFETY: "Food Safety",
  MANUAL_HANDLING: "Manual Handling",
  RAW_MATERIALS_INGREDIENTS: "Raw Materials & Ingredients",
  FORMULATIONS: "Formulations",
  PRODUCTION: "Production",
  PACKAGING: "Packaging",
  EQUIPMENT_MAINTENANCE: "Equipment & Maintenance",
  CLEANING_SANITATION: "Cleaning & Sanitation",
  ENVIRONMENTAL_MONITORING: "Environmental Monitoring",
  WHS: "Workplace Health & Safety (WHS)",
  TEAMWORK_COMMUNICATION: "Teamwork & Communication",
  TRAINING_INDUCTION: "Training & Induction",
  SOPS: "SOPs",
  POLICIES_PROCEDURES: "Policies & Procedures",
};

export const KB_CATEGORY_CLASS: Record<KbCategory, string> = {
  BLENDING_SOP: "bg-info/10 text-info border-info/30",
  MACHINE_TROUBLESHOOTING: "bg-warning/10 text-warning border-warning/30",
  MAINTENANCE_CLEANING: "bg-success/10 text-success border-success/30",
  SAFETY: "bg-danger/10 text-danger border-danger/30",
  PARTS: "bg-surface-muted text-muted-foreground border-border",
  QUALITY_CONTROL: "bg-info/10 text-info border-info/30",
  QUALITY_ASSURANCE: "bg-primary/10 text-primary border-primary/30",
  HACCP: "bg-warning/10 text-warning border-warning/30",
  SQF: "bg-success/10 text-success border-success/30",
  GMP: "bg-danger/10 text-danger border-danger/30",
  GDP: "bg-surface-muted text-muted-foreground border-border",
  FOOD_SAFETY: "bg-info/10 text-info border-info/30",
  MANUAL_HANDLING: "bg-primary/10 text-primary border-primary/30",
  RAW_MATERIALS_INGREDIENTS: "bg-warning/10 text-warning border-warning/30",
  FORMULATIONS: "bg-success/10 text-success border-success/30",
  PRODUCTION: "bg-danger/10 text-danger border-danger/30",
  PACKAGING: "bg-surface-muted text-muted-foreground border-border",
  EQUIPMENT_MAINTENANCE: "bg-info/10 text-info border-info/30",
  CLEANING_SANITATION: "bg-primary/10 text-primary border-primary/30",
  ENVIRONMENTAL_MONITORING: "bg-warning/10 text-warning border-warning/30",
  WHS: "bg-danger/10 text-danger border-danger/30",
  TEAMWORK_COMMUNICATION: "bg-success/10 text-success border-success/30",
  TRAINING_INDUCTION: "bg-info/10 text-info border-info/30",
  SOPS: "bg-primary/10 text-primary border-primary/30",
  POLICIES_PROCEDURES: "bg-surface-muted text-muted-foreground border-border",
};
