import type { KbCategory } from "@/generated/prisma";
import type { Lang } from "./i18n/translations";

export const KB_CATEGORY_LABEL: Record<KbCategory, string> = {
  BLENDING_SOP: "Blending SOP",
  MACHINE_TROUBLESHOOTING: "Machine Troubleshooting",
  MAINTENANCE_CLEANING: "Maintenance & Cleaning",
  SAFETY: "Safety",
  PARTS: "Parts & Tooling",
  QUALITY_CONTROL: "Quality Control",
  QUALITY_ASSURANCE: "Quality Assurance",
  HACCP: "HACCP",
  SQF: "SQF",
  GMP: "GMP",
  GDP: "Good Documentation Practice (GDP)",
  FOOD_SAFETY: "Food Safety",
  MANUAL_HANDLING: "Manual Handling",
  RAW_MATERIALS_INGREDIENTS: "Raw Materials & Ingredients",
  FORMULATIONS: "Formulations",
  PRODUCTION: "Production",
  PACKAGING: "Packaging",
  EQUIPMENT_MAINTENANCE: "Equipment & Maintenance",
  CLEANING_SANITATION: "Cleaning & Sanitation",
  ENVIRONMENTAL_MONITORING: "Environmental Monitoring",
  WHS: "Workplace Health & Safety (WHS)",
  TEAMWORK_COMMUNICATION: "Teamwork & Communication",
  TRAINING_INDUCTION: "Training & Induction",
  SOPS: "SOPs",
  POLICIES_PROCEDURES: "Policies & Procedures",
};

export const KB_CATEGORY_LABEL_SI: Record<KbCategory, string> = {
  BLENDING_SOP: "මිශ්‍රණය SOP",
  MACHINE_TROUBLESHOOTING: "යන්ත්‍ර දෝෂ නිරාකරණය",
  MAINTENANCE_CLEANING: "නඩත්තුව සහ පිරිසිදුකිරීම",
  SAFETY: "ආරක්ෂාව",
  PARTS: "අමතර කොටස් සහ මෙවලම්",
  QUALITY_CONTROL: "තත්ත්ව පාලනය",
  QUALITY_ASSURANCE: "තත්ත්ව සහතිකකරණය",
  HACCP: "HACCP",
  SQF: "SQF",
  GMP: "GMP",
  GDP: "යහපත් ලේඛන පිළිවෙත (GDP)",
  FOOD_SAFETY: "ආහාර ආරක්ෂාව",
  MANUAL_HANDLING: "අතින් හැසිරවීම",
  RAW_MATERIALS_INGREDIENTS: "අමුද්‍රව්‍ය",
  FORMULATIONS: "සූත්‍රීකරණ",
  PRODUCTION: "නිෂ්පාදනය",
  PACKAGING: "පැකේජීකරණය",
  EQUIPMENT_MAINTENANCE: "උපකරණ නඩත්තුව",
  CLEANING_SANITATION: "පිරිසිදුකිරීම හා සනීපාරක්ෂාව",
  ENVIRONMENTAL_MONITORING: "පාරිසරික නිරීක්ෂණය",
  WHS: "වැඩපොළ සෞඛ්‍ය හා ආරක්ෂාව (WHS)",
  TEAMWORK_COMMUNICATION: "කණ්ඩායම් වැඩ සහ සන්නිවේදනය",
  TRAINING_INDUCTION: "පුහුණුව සහ අභ්‍යාසය",
  SOPS: "SOPs",
  POLICIES_PROCEDURES: "ප්‍රතිපත්ති හා ක්‍රියාපටිපාටි",
};

export function getCategoryLabel(category: KbCategory, lang: Lang): string {
  return lang === "si" ? KB_CATEGORY_LABEL_SI[category] : KB_CATEGORY_LABEL[category];
}

/** Tinted glass-style badges — matches Dhanu Brain's dark UI (transparent color-500/10 fills, ring-inset borders). */
export const KB_CATEGORY_CLASS: Record<KbCategory, string> = {
  BLENDING_SOP: "border-blue-400/30 bg-blue-400/10 text-blue-300",
  MACHINE_TROUBLESHOOTING: "border-amber-400/30 bg-amber-400/10 text-amber-300",
  MAINTENANCE_CLEANING: "border-emerald-400/30 bg-emerald-400/10 text-emerald-300",
  SAFETY: "border-red-400/30 bg-red-400/10 text-red-300",
  PARTS: "border-white/[0.12] bg-white/[0.05] text-zinc-400",
  QUALITY_CONTROL: "border-blue-400/30 bg-blue-400/10 text-blue-300",
  QUALITY_ASSURANCE: "border-violet-400/30 bg-violet-400/10 text-violet-300",
  HACCP: "border-amber-400/30 bg-amber-400/10 text-amber-300",
  SQF: "border-emerald-400/30 bg-emerald-400/10 text-emerald-300",
  GMP: "border-red-400/30 bg-red-400/10 text-red-300",
  GDP: "border-white/[0.12] bg-white/[0.05] text-zinc-400",
  FOOD_SAFETY: "border-blue-400/30 bg-blue-400/10 text-blue-300",
  MANUAL_HANDLING: "border-violet-400/30 bg-violet-400/10 text-violet-300",
  RAW_MATERIALS_INGREDIENTS: "border-amber-400/30 bg-amber-400/10 text-amber-300",
  FORMULATIONS: "border-emerald-400/30 bg-emerald-400/10 text-emerald-300",
  PRODUCTION: "border-red-400/30 bg-red-400/10 text-red-300",
  PACKAGING: "border-white/[0.12] bg-white/[0.05] text-zinc-400",
  EQUIPMENT_MAINTENANCE: "border-blue-400/30 bg-blue-400/10 text-blue-300",
  CLEANING_SANITATION: "border-violet-400/30 bg-violet-400/10 text-violet-300",
  ENVIRONMENTAL_MONITORING: "border-amber-400/30 bg-amber-400/10 text-amber-300",
  WHS: "border-red-400/30 bg-red-400/10 text-red-300",
  TEAMWORK_COMMUNICATION: "border-emerald-400/30 bg-emerald-400/10 text-emerald-300",
  TRAINING_INDUCTION: "border-blue-400/30 bg-blue-400/10 text-blue-300",
  SOPS: "border-violet-400/30 bg-violet-400/10 text-violet-300",
  POLICIES_PROCEDURES: "border-white/[0.12] bg-white/[0.05] text-zinc-400",
};
